lukasturcani/stk

- src/stk/databases/mongo_db/constructed_molecule.py
- src/stk/databases/mongo_db/molecule.py
MongoDb's caching of `_put()` was not working, because `insert_one()` modified the `HashableDict` which was placed in the `lru_cache`. This resulted in the `HashableDict` in the `lru_cache` being different to the a clean `HashableDict` passed to `_put()`.
> Caching fix

- .travis.yml
- src/stk/databases/mongo_db/value.py
- tests/databases/value/fixtures/mongo_db.py
- tests/environment.yml
This PR replaces the single `lru_cache_size` argument with two separate `cach_size` arguments. This has the benefit of allowing the user to toggle each cache individually. For example, you might want to allow caching for the `put` method, while preventing caching for the `get` method. You might want to prevent caching in the `get` method exclusively in cases where you are adding the same molecule to the database, but in each case it has a different position matrix. In such a situation, the `get` method would not reflect the updates to the database if caching is turned on.
This PR also makes the tests use an actual MongoDb for testing - because it is easier to test than using a Mock database.
> Deprecate ValueMongoDb arguments.

- src/stk/molecular/key_makers/utilities.py
Treating warnings as errors led to some valid molecules causing
errors because their stereochemistry could not be assigned.
See #213 on GitHub.
> Not treating Inchi warnings as errors.

- src/stk/molecular/molecules/constructed_molecule.py
- tests/molecular/molecules/molecule/with_canonical_atom_ordering/conftest.py
ConstructedMolecule.with_canonical_atom_ordering() now
also makes building blocks have canonical atom ordering.
This is necessary for databases which deposit constructed
molecules, and which require canonical ordering of all
molecules deposited. So when a ConstructedMolecule is
deposited, together with its building blocks, everyting is
canonical.
> Fix with_canonical_atom_ordering().

- src/stk/molecular/topology_graphs/macrocycle/macrocycle.py
Related Issues: #330
Requested Reviewers: @lukasturcani
This PR introduces an error to let the user know (in a hard way, because the output is nonsense) that alignment is not supported for Macrocycles formed from only 2 building blocks and 1 repeat unit. This is an edge use-case that I think can be fixed, with large rewrites of the Macrocycle class. A 2 building block Macrocycle also makes less sense, then using a different topology for that molecule.
> Add ValueError for Macrocycle from 2 BBs

- src/stk/molecular/periodic_info.py
Related Issues: #307 
Requested Reviewers: @andrewtarzia 
When `PeriodicInfo` is being initialized it is not making a copy of
the arrays it is being given. This means thats if those arrays get
changed on the outside, the internal state of `PeriodicInfo` also gets
corrupted. Similarly, when the `get` methods are called, the internal
state is returned directly, rather than a copy of the arrays. If
someone calls `get` and then changes the value in the returned array,
they will also change the internal state of `PeriodicInfo`.
This commit just makes sure to make a copy of the arrays which are
received as input and returned as output.
> Plug PeriodicInfo state leak

- docs/source/stk.molecular.topology_graphs.topology_graph.optimizers.rst
- docs/source/stk.molecular.topology_graphs.topology_graph.optimizers.spinner.rst
- setup.py
- src/stk/molecular/topology_graphs/host_guest/complex.py
- src/stk/molecular/topology_graphs/topology_graph/optimizers/__init__.py
- src/stk/molecular/topology_graphs/topology_graph/optimizers/optimizer.py
- src/stk/molecular/topology_graphs/topology_graph/optimizers/spinner.py
- tests/docker/environment.yml
- tests/molecular/molecules/molecule/fixtures/host_guest/complex.py
Simply add another optimizer called Spinner, which is made to optimize/generate conformers of host-guest pairs. This is most crucial for systems with multiple guests that may have overlapping structures.
I followed the same approach as the mchammer optimizers (effectively the same interface and code).
Adds a new dependency. It is small, but worth making the decision about its inclusion.
minimum working example (tests also included) - compare the two output structures.:
```python
import stk
host = stk.ConstructedMolecule(
topology_graph=stk.cage.FourPlusSix(
building_blocks=(
stk.BuildingBlock('BrCCBr', [stk.BromoFactory()]),
stk.BuildingBlock(
smiles='BrCC(Br)CBr', …
```
> Implement Spinner optimizer with docs and tests.

- docs/source/basic_ea_example.rst
- docs/source/basic_examples.rst
- docs/source/construction_overview.rst
Related Issues: #349 
Requested Reviewers: @lukasturcani
This PR simply replaces examples of `Molecule.write(path)` with `stk.Writer().write(molecule, path)` in prominent places that do not affect convenience (e.g. in the EA runs, some places should stay in the original version because of actual convenience and unclear file type expectations).
> User Writer class in docs.

- src/stk/molecular/molecules/building_block.py
- tests/molecular/molecules/building_block/test_get_num_placers.py
Related Issues: #376
Requested Reviewers: @andrewtarzia
A new method, `BuildingBlock.get_num_placers()` has been added. This
is necessary because sometimes the number of placer atoms is necessary,
for example, by unaligning vertices, which needs to check the number of
placer atoms, in order to determine if the unaligning vertex should be
used. Previously all the placer ids would have to be iterated though
with `BuildingBlock.get_placer_ids()`, which is both ugly and less
performant.
> Add BuildingBlock.get_num_placers()

- .flake8
- .github/workflows/tests.yml
Use a config file for flake8, instead of specifying options in the
workflow file. This ensures that flake8 uses the same options regardless
of if it is run manually or in CI.
> Use a flake8 config file

- src/stk/molecular/molecules/building_block.py
Related Issues: #396
Added additional notes section in the docstring to explain that users should kekulize their molecule prior to calling the `init_form_rdkit_mol` method. It also explains the consequences of not doing so (bond orders changed to 1).
Also fixed a capital letter. 
As this does not change any code, there will be no issues with this code change.
> init_from_rdkit_mol Docstring Edit

- Makefile
- setup.py
I've added a Makefile which can be used with `make check` so that
all the tests, and linting checks are performed in one go, rather
than the developer having to call them individually. This is purely
to help the local development workflow, it is not to be used with CI.
> Add a Makefile for quickly running all checks

- src/stk/molecular/molecules/building_block.py
Related Issues: #446 
Requested Reviewers: @andrewtarzia 
Removes the note that users can load `pdb` files from the docstring of 
`init_from_file`, in order to stop new users from using these files for loading
molecules. Loading will still work for now, but users will receive a `FutureWarning`
telling them that they should switch to `.mol` files.
The reason this deprecation is necessary is that `pdb` files do not encode bond
orders and the loaded building blocks may therefore have wrong or unexpected
connectivity. By explicitly not supporting this file type we make sure our users
carefully consider the bonding of their molecules and avoid surprises.
> Add deprecation notice for `pdb` reading

- mypy.ini
- src/stk/molecular/key_makers/inchi.py
- src/stk/molecular/key_makers/inchi_key.py
- src/stk/molecular/key_makers/smiles.py
- src/stk/molecular/key_makers/utilities.py
Requested Reviewers: @andrewtarzia
Refactored the key makers to explicitly provide type hints rather
than rely on the default implementation. It is sometimes useful to
be able to rely on the more specific type of the key.
> Add type hints

- .github/workflows/tests.yml
Database dump commands were not working. Dumping the databases has not provided a lot of utility. Instead of fixing, it is easier to remove.
Co-authored-by: Lukas Turcani <lukasturcani@mailbox.org>
> Remove MongoDB database dump from tests

- .gitignore
- src/stk/molecular/writers/mdl_mol.py
- src/stk/molecular/writers/pdb.py
- src/stk/molecular/writers/xyz.py
``xyz``, ``pdb``, and ``mdl_mol`` can now be initialized using pathlib.Paths.
Updated the type hints to allow pathlibs and imported pathlib
> Implement initialization with pathlib.Path

- justfile
Makes it easier to start a MongoDB instance (which is
necessary for running all the tests). Running Mongo in
docker avoids the pain associated with setting up a local
Mongo server.
> Add a mongo command

- README.rst
- docs/source/index.rst
If the user is in an old environment, the old version of stk will get 
installed anyway.
> Remove unnecessary pip install

- justfile
- src/stk/_internal/constructed_molecule.py
- src/stk/_internal/construction_state/molecule_state/molecule_state.py
- src/stk/_internal/topology_graphs/cage/cage.py
- src/stk/_internal/topology_graphs/cage/cage_construction_state.py
- src/stk/_internal/topology_graphs/cof/cof.py
- src/stk/_internal/topology_graphs/host_guest/complex.py
Related Issues: #524
The existing implementation was overwriting the existing host
vertex if the guest was the same building block as the vertex.
Fix this by appending to the list of vertices that a given building
block is attached to.
> Fix complex

- docs/source/basic_examples.rst
- pyproject.toml
Just adding a small example to raise awareness of the utility of the tool. I am happy to change the scope as necessary.
Note that I have not made the python code testable to avoid the need for a new dev dependancy,
> Add a chemiscope example.
