lukasturcani/stk

stk/utilities/utilities.py
=> handle UTF-8 encoding on windows

tests/test_xtb.py
=> Fixing tests

src/stk/calculators/energy/energy_calculators.py, src/stk/calculators/optimization/optimizers.py, tests/external_software/test_xtb.py
Fixes issue #49 by setting shell=True in all cases.
=> use shell in all cases. modify tests

src/stk/molecular/molecules/molecule.py
=> Added clone method to Molecule.

src/stk/molecular/molecules/building_block.py, tests/molecular/molecules/test_building_block.py
=> Add init from molecule

src/stk/calculators/base_calculators.py, src/stk/calculators/calculator.py
=> added calculator

src/stk/calculators/calculator.py, src/stk/calculators/energy/energy_calculators.py
after calculator
@stevenbennett96
=> Energy calculator

src/stk/calculators/base_calculators.py, src/stk/calculators/energy/energy_calculators.py, src/stk/calculators/optimization/optimizers.py
=> removed duplication

docs/source/compound_crossers.rst, docs/source/compound_mutators.rst, src/stk/__init__.py, src/stk/ea/fitness_normalizers/sequence.py, src/stk/ea/selection/selectors/selector.py
Added document title, so that links in the sidebar appear in subheadings.
=> Sidebar sections

src/stk/molecular/molecules/building_block.py
=> Added deprecation warning and new parameter.

src/stk/molecular/topology_graphs/metal_complex/square_planar/square_planar.py, tests/molecular/molecules/molecule/fixtures/metal_complex/square_planar/square_planar.py
=> Add SquarePlanar and test

src/stk/molecular/topology_graphs/metal_complex/square_planar/bidentate_square_planar.py, tests/molecular/molecules/molecule/fixtures/metal_complex/square_planar/bidentate_square_planar.py
=> Add BidentateSquarePlanar and test

src/stk/molecular/topology_graphs/metal_complex/square_planar/cis_protected_square_planar.py, tests/molecular/molecules/molecule/fixtures/metal_complex/square_planar/cis_protected_square_planar.py
=> Add CisProtectedSquarePlanar and test

src/stk/molecular/topology_graphs/metal_complex/octahedral/octahedral.py, tests/molecular/molecules/molecule/fixtures/metal_complex/octahedral/octahedral.py
=> Add Octahedral and test

src/stk/molecular/topology_graphs/metal_complex/octahedral/octahedral_delta.py, tests/molecular/molecules/molecule/fixtures/metal_complex/octahedral/octahedral_delta.py
=> Add OctahedralDelta and test

src/stk/molecular/topology_graphs/metal_complex/octahedral/octahedral_lambda.py, tests/molecular/molecules/molecule/fixtures/metal_complex/octahedral/octahedral_lambda.py
=> Add OctahedralLambda and test

src/stk/molecular/topology_graphs/metal_complex/porphyrin/porphyrin.py, tests/molecular/molecules/molecule/fixtures/metal_complex/porphyrin/porphyrin.py
=> Add Porphyrin and test

src/stk/molecular/topology_graphs/metal_complex/paddlewheel/paddlewheel.py, tests/molecular/molecules/molecule/fixtures/metal_complex/paddlewheel/paddlewheel.py
=> Add Paddlewheel and test

src/stk/databases/value.py, src/stk/molecular/molecules/utilities.py
=> Fix dative bond ordering

src/stk/databases/mongo_db/molecule.py
=> changed default parameter

src/stk/molecular/functional_groups/functional_groups/alkene.py
=> Fixed wrong attribute name.

.travis.yml
=> Added EA jobs.

src/stk/molecular/molecules/molecule/molecule.py
#240 
@andrewtarzia 
@stevenbennett96
=> Change molecule repr.

src/stk/ea/evolutionary_algorithm/implementations/implementation.py, src/stk/ea/mutation/mutators/compound/random.py, src/stk/ea/mutation/mutators/molecule/mutator.py
=> Let Mutator.mutate() return None.

.github/pull_request_template.md, .github/workflows/tests.yml
=> Update PR template

tests/environment.yml
=> Remove redundant option

tests/molecular/topology_graphs/conftest.py
Related Issues: https://github.com/lukasturcani/stk/pull/313#discussion_r620300934
Requested Reviewers: @andrewtarzia 
A pretty self explanatory improvement to the docstrings.
=> Add docstrings

src/stk/databases/mongo_db/constructed_molecule.py, src/stk/databases/mongo_db/molecule.py, src/stk/databases/mongo_db/value.py, src/stk/molecular/molecules/building_block.py, src/stk/molecular/topology_graphs/macrocycle/macrocycle.py
Requested Reviewers: @andrewtarzia 
Does a bunch of backwards incompatible changes the users were
warned about ages ago.
=> Remove old features

.github/workflows/tests.yml, .readthedocs.yml, docs/requirements.txt, docs/source/conf.py
Because of the introduction of type hints, libraries can no longer be
mocked for the purposes of documentation. This is because the the types
in the library need to actually imported for the documentation
compilation to work. As a result, this commit removes all things
related to the mocking of modules from the repo. This includes the
requirements file `docs/requirements.txt` because all the dependencies
already exist in `tests/docker/environment.yml`. The dependencies are
there already because we use doctest, so any dependencies required
for Sphinx are already present in the test environment.
The `MOCK_MODULES` variable has been removed from
`.github/workflows/tests.yml` because it has been removed from
`docs/source/conf.py` because the mocking has been removed.
=> Stop mocking modules

src/stk/molecular/topology_graphs/polymer/linear/linear.py
=> Make class private

src/stk/molecular/topology_graphs/metal_complex/octahedral/octahedral.py, src/stk/molecular/topology_graphs/metal_complex/paddlewheel/paddlewheel.py, src/stk/molecular/topology_graphs/metal_complex/square_planar/bidentate_square_planar.py, src/stk/molecular/topology_graphs/metal_complex/square_planar/cis_protected_square_planar.py, src/stk/molecular/topology_graphs/metal_complex/square_planar/square_planar.py
Simple PR to choose better example metal_complex structures for the docs.
=> Update example metal complexes.

src/stk/molecular/key_makers/inchi.py, src/stk/molecular/key_makers/inchi_key.py, src/stk/molecular/key_makers/molecule.py, src/stk/molecular/key_makers/smiles.py, src/stk/molecular/key_makers/utilities.py
Add type hints for `MoleculeKeyMaker`.
=> Add type hints

src/stk/molecular/topology_graphs/cage/metal_topologies/m2l4_lantern.py, src/stk/molecular/topology_graphs/cage/metal_topologies/m3l3_triangle.py, src/stk/molecular/topology_graphs/cage/metal_topologies/m4l4_square.py, src/stk/molecular/topology_graphs/cage/metal_topologies/m4l4_tetrahedron.py, src/stk/molecular/topology_graphs/cage/metal_topologies/m4l6_tetrahedron_spacer.py, src/stk/molecular/topology_graphs/cage/metal_topologies/m6l2l3_prism.py, src/stk/molecular/topology_graphs/cage/metal_topologies/m8l6_cube.py, src/stk/molecular/topology_graphs/cage/two_plus_four/five_plus_ten.py, src/stk/molecular/topology_graphs/cage/two_plus_four/four_plus_eight.py, src/stk/molecular/topology_graphs/cage/two_plus_four/three_plus_six.py, src/stk/molecular/topology_graphs/cage/two_plus_four/two_plus_four.py
Related Issues: #417 
Just changing the molecules used in the examples for topology graphs listed in the issue to be more reasonable to what they may actually be used for,
=> Update m6l2l3 example.

src/stk/molecular/topology_graphs/host_guest/complex.py
The `guest`, `guest_start` and other related parameters have
been removed from the initializer of the `Complex` topology graph.
Users were warned about this deprecation a long time ago so this
should not come as a surprise.
The other change is that the `guests` parameter is now no longer
optional. It was only optional so that users could continue to use
the old API, but now that the old API has been removed, the `guests`
parameter will always be required. After all, it would not make sense
to have a host-guest complex without a guest!
The other thing I did was that the type hint now correctly allows users
to provide a single `Guest` instance, rather than just an `Iterable`
of `Guest` instances. This was just an error in the previous type hint.
=> Remove old API from `Complex`

README.rst
=> Add new paper to using stk section of README

README.rst
Add recent papers using stk and other references on cages.
=> Update README papers.

src/stk/_internal/ea/evolutionary_algorithm/implementations/implementation.py, src/stk/_internal/ea/fitness_calculators/fitness_calculator.py, src/stk/_internal/ea/fitness_calculators/fitness_function.py, src/stk/_internal/ea/fitness_calculators/property_vector.py, src/stk/_internal/ea/plotters/progress.py, tests/ea/fitness_calculator/test_caching/case_data.py, tests/ea/fitness_calculator/test_caching/conftest.py, tests/ea/fitness_calculator/test_caching/fixtures/fitness_function.py, tests/ea/fitness_calculator/test_caching/fixtures/property_vector.py, tests/ea/fitness_calculator/test_caching/fixtures/utilities.py, tests/ea/fitness_calculator/test_caching/test_caching.py
Related Issues: #473  
Requested Reviewers: @andrewtarzia  
=> Fitness functions use MoleculeRecord

docs/source/index.rst
There was an issue with the formatting on `index.rst`. Fixed now.
=> Fix index.rst.

.github/workflows/publish_release.yml
Handles the move to 2FA for pypi.
=> Update action with 2FA.
